- name: Ensure mysql server is installed
  yum: name=mysql-server state=present

- name: Ensure mysql python is installed
  yum: name=MySQL-python state=present


- name: Ensure selinux python bindings are installed
  yum: name=libselinux-python state=present

- name: Ensure cloudstack specfic my.cnf lines are present
  lineinfile: dest=/etc/my.cnf regexp={{item}} insertafter=”symbolic-links=0″ line={{item}}
  with_items:
    - skip-name-resolve
    - default-time-zone='+00:00'
    - innodb_rollback_on_timeout=1
    - innodb_lock_wait_timeout=600
    - max_connections=350
    - log-bin=mysql-bin
    - binlog-format='ROW'


- name: Ensure MySQL service is started
  service: name=mysqld state=started

- name: Ensure MySQL service is enabled at boot
  service: name=mysqld enabled=yes

- name: Make sure root password is set
  command: mysqladmin -u root password {{ mysql_root_password }}
  ignore_errors: yes

- name: Ensure root has sufficient privileges
  mysql_user: login_user=root login_password={{ mysql_root_password }} user=root host=% password= {{ mysql_root_password }} priv=*.*:GRANT,ALL state=present
